DefaultContentLanguage = "en"
baseURL = "https://juan-torresmunguia.netlify.app"
theme = "hugo-apero"
languageCode = "en"
title = "Juan TORRES MUNGUÍA, PhD"
author = "Juan TORRES MUNGUÍA, PhD"
copyright = "" 
googleAnalytics = ""
disqusShortname = "" 
metaDataFormat = "yaml"
footnoteReturnLinkContents = "&#8617;" # ↩
paginate = 4
preserveTaxonomyNames = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  
    hardwraps = false 
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.highlight]
    # one of: https://xyproto.github.io/splash/docs/ 
    style = "github"
    
[params]
  orgName = "Juan TORRES MUNGUÍA"
  orgLocal = "Saltillo, MEXICO"
  description = ""
  favicon = "/img/icon_basic.jpeg"
  logo = ""
  mainSections = ["About", "Publications", "Talks", "Blog", "Contact"]
  navallcaps = true
  socialInHeader = false
  socialInFooter = true
  sharing_image = ""
  twitter = "jtorresmunguia"
  theme = "paper"
  custom_theme = "hex-colors" 
  customtextFontFamily = "Bitter"
  customheadingFontFamily = "Bitter"
  textFontFamily = "Bitter"
  headingFontFamily = "Bitter"

  [params.utterances]
    use_utterances = true
    repo_name = "jatorresmunguia/juan-torresmunguia"
    issue_term = "pathname" # url, pathname, or title
    theme = "github-light"
    label = "comments :crystal_ball:"

  [params.math]
    renderer = "katex" # one of "mathjax" / "katex" 

  [[params.social]]
      icon      = "github" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://github.com/jatorresmunguia"
  [[params.social]]
      icon      = "twitter" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://twitter.com/jtorresmunguia"
  [[params.social]]
      icon      = "orcid" # icon name without the 'fa-'
      icon_pack = "ai"
      url       = "https://orcid.org/0000-0003-3432-6941"
  [[params.social]]
      icon      = "google-scholar" # icon name without the 'fa-'
      icon_pack = "ai"
      url       = "https://scholar.google.com/citations?hl=es&user=VelzdlMAAAAJ"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  # Configure header 
  [[menu.header]]
    name = "About"
    title = "About"
    url = "/about/"
    weight = 1
  [[menu.header]]
    name = "Publications"
    title = "Publications" 
    url = "/publications/"
    weight = 2
  [[menu.header]]
    name = "Talks"
    title = "Talks"
    url = "/talk/"
    weight = 3
#  [[menu.header]]
#    name = "Blog"
#    title = "Blog"
#    url = "/blog/"
#    weight = 4
  [[menu.header]]
    name = "DataViz"
    title = "A collection of data visualizations"
    url = "/collection/"
    weight = 5
  [[menu.header]]
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = 6
    
  # Configure footer  
  [[menu.footer]]
    name = "License"
    title = "License"
    url = "/license/"
    weight = 1
  [[menu.footer]]
    name = "Contact"
    title = "Contact form"
    url = "/contact/"
    weight = 2

# see https://gohugo.io/about/hugo-and-gdpr/    
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
