---
title: "A global dataset of pandemic- and epidemic-prone disease outbreaks"
author: "Juan Armando Torres Munguía"
summary: "The Centre for Research on the Epidemiology of Disasters (CRED), in partnership with North-West University (NWU) in Potchefstroom, South Africa, successfully organized the second meeting Scientific and Technical Advisory Group (STAG) on March 18–19, 2024. This event took place in Potchefstroom, focusing on disaster research within the framework of the Emergency Events Database (EM-DAT) project, with the support of the Bureau for Humanitarian Assistance of the United States Agency for International Development (BHA/USAID). Throughout the meeting, the panel delved into a range of important topics pertinent to EM-DAT, such as the launch of the new EM-DAT platform, strategies for data automation, local and regional data collection efforts (R-EMDAT), refining heatwave data gathering practices, and future directions and recommendations for the EM-DAT initiative."
date: "2024-03-19"
featured: false
show_post_time: false
show_author_byline: false
event: "EM-DAT International Disaster Database. Scientific & Technical Advisory Group (STAG) Meeting"
event_url: "https://www.emdat.be/news/2024/03/stag2024/"
location: "Potchefstroom, South Africa"
keywords: "open data; outbreaks; diseases; epidemics; pandemics"
draft: false
# layout options: single, single-sidebar
layout: single-talk
links:
- icon: chalkboard
  icon_pack: fas
  name: slides
  url: "https://jatorresmunguia.github.io/slides_dataset_disease_outbreaks_stag_2024/#1"
---

<h3 style="text-align: justify;"> About the event </h3>
<p style="text-align: justify;">
  The Centre for Research on the Epidemiology of Disasters (CRED), in partnership with North-West University (NWU) in Potchefstroom, South Africa, successfully organized the second meeting Scientific and Technical Advisory Group (STAG) on March 18–19, 2024. This event took place in Potchefstroom, focusing on disaster research within the framework of the Emergency Events Database (EM-DAT) project, with the support of the Bureau for Humanitarian Assistance of the United States Agency for International Development (BHA/USAID). Throughout the meeting, the panel delved into a range of important topics pertinent to EM-DAT, such as the launch of the new EM-DAT platform, strategies for data automation, local and regional data collection efforts (R-EMDAT), refining heatwave data gathering practices, and future directions and recommendations for the EM-DAT initiative.
</p>

<h4 style="text-align: justify;"><a href="https://www.emdat.be/stag/" target="_blank"> Click here to read more about the event</a></h4>
